### ISSUE TITLE
Code error from cdd.Matrix (pycddlib)

### ISSUE THREAD

**Issue by smbct** [heirung/pytope#7]
The error occurs with the script demo.py :

 ```
Traceback (most recent call last):
  File "***/demo.py", line 36, in <module>
    print('V =\n', P3.V)
  File "/home/***/.local/lib/python3.10/site-packages/pytope/polytope.py", line 171, in V
    return self._get_V()
  File "/home/***/.local/lib/python3.10/site-packages/pytope/polytope.py", line 179, in _get_V
    self.determine_V_rep()
  File "/home/***/.local/lib/python3.10/site-packages/pytope/polytope.py", line 300, in determine_V_rep
    H = cdd.Matrix(b_mA, number_type='float')
TypeError: __init__() takes exactly 0 positional arguments (1 given)
```
package versions (installed with pip):

```
Name: pytope
Version: 0.0.4

Name: pycddlib
Version: 3.0.0
```

**Comment by TheLastPixie** [comment]
You might have figured it out by now, but alas the library (pytope) is a bit old so use an older version of pycddlib:
```
!pip uninstall -y pycddlib 
!pip install "pycddlib<3"
```

**Comment by smbct** [comment]
Thank you for the reply! I eventually decided to use pycddlib directly, which better corresponds to my needs. I am however glad to see a way of working it out. Specifying this dependency+version numbering in the documentation might be a good thing ?
